<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\application\EventStorming.BoardModelling\EventStorming.BoardModelling.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="element-types.json" LogicalName="element-types.json" />
  </ItemGroup>

</Project>
