// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace EventStorming.Specs.Features.Teams
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class InvitationsFeature : object, Xunit.IClassFixture<InvitationsFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Teams", "Invitations", "  Owners invite people to their team, either by email or with a link they share. " +
                "An email invitation is\r\n  for one address and works once; a link works for anyon" +
                "e who has it until it expires after 7 days or\r\n  is revoked.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Invitations.feature"
#line hidden
        
        public InvitationsFeature(InvitationsFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("the time is \"2026-09-25T10:00:00Z\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("Ana owns the team \"Checkout squad\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Teams/Invitations.feature.ndjson", 18);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Inviting by email sends the link to that address")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Invitations")]
        [global::Xunit.TraitAttribute("Description", "Inviting by email sends the link to that address")]
        public async global::System.Threading.Tasks.Task InvitingByEmailSendsTheLinkToThatAddress()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Inviting by email sends the link to that address", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Create an invitation", null, tagsOfRule);
#line 12
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 13
      await testRunner.WhenAsync("Ana invites \"bo@example.com\" to \"Checkout squad\" as editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
      await testRunner.ThenAsync("the request succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 15
      await testRunner.AndAsync("an invitation email is sent to \"bo@example.com\" from Ana", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
      await testRunner.AndAsync("only the hash of the invitation token is stored", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A link invitation sends no email")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Invitations")]
        [global::Xunit.TraitAttribute("Description", "A link invitation sends no email")]
        public async global::System.Threading.Tasks.Task ALinkInvitationSendsNoEmail()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A link invitation sends no email", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Create an invitation", null, tagsOfRule);
#line 18
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 19
      await testRunner.WhenAsync("Ana creates an invitation link to \"Checkout squad\" as viewer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
      await testRunner.ThenAsync("the request succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 21
      await testRunner.AndAsync("no invitation email is sent", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Only Owners can invite")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Invitations")]
        [global::Xunit.TraitAttribute("Description", "Only Owners can invite")]
        public async global::System.Threading.Tasks.Task OnlyOwnersCanInvite()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Only Owners can invite", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Create an invitation", null, tagsOfRule);
#line 23
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 24
      await testRunner.GivenAsync("Bo is an editor of \"Checkout squad\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 25
      await testRunner.WhenAsync("Bo creates an invitation link to \"Checkout squad\" as editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
      await testRunner.ThenAsync("the request is refused as \"forbidden\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="The role must be one the team knows")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Invitations")]
        [global::Xunit.TraitAttribute("Description", "The role must be one the team knows")]
        public async global::System.Threading.Tasks.Task TheRoleMustBeOneTheTeamKnows()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The role must be one the team knows", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Create an invitation", null, tagsOfRule);
#line 28
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 29
      await testRunner.WhenAsync("Ana creates an invitation link to \"Checkout squad\" as admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
      await testRunner.ThenAsync("the request fails with \"unknown-role\" on \"role\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 31
      await testRunner.AndAsync("every failure says how to fix it", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Revoked invitations are no longer listed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Invitations")]
        [global::Xunit.TraitAttribute("Description", "Revoked invitations are no longer listed")]
        public async global::System.Threading.Tasks.Task RevokedInvitationsAreNoLongerListed()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Revoked invitations are no longer listed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("See and revoke open invitations", null, tagsOfRule);
#line 35
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 36
      await testRunner.GivenAsync("Ana has created an invitation link to \"Checkout squad\" as editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 37
      await testRunner.AndAsync("Ana has invited \"cy@example.com\" to \"Checkout squad\" as viewer", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
      await testRunner.WhenAsync("Ana revokes the invitation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
      await testRunner.AndAsync("Ana lists the invitations of \"Checkout squad\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
      await testRunner.ThenAsync("1 invitation is open", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Expired invitations are no longer listed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Invitations")]
        [global::Xunit.TraitAttribute("Description", "Expired invitations are no longer listed")]
        public async global::System.Threading.Tasks.Task ExpiredInvitationsAreNoLongerListed()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Expired invitations are no longer listed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("See and revoke open invitations", null, tagsOfRule);
#line 42
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 43
      await testRunner.GivenAsync("Ana has created an invitation link to \"Checkout squad\" as editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 44
      await testRunner.AndAsync("8 days pass", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
      await testRunner.WhenAsync("Ana lists the invitations of \"Checkout squad\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 46
      await testRunner.ThenAsync("0 invitations are open", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Anyone holding the link can see what it is for")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Invitations")]
        [global::Xunit.TraitAttribute("Description", "Anyone holding the link can see what it is for")]
        public async global::System.Threading.Tasks.Task AnyoneHoldingTheLinkCanSeeWhatItIsFor()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Anyone holding the link can see what it is for", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Preview an invitation", null, tagsOfRule);
#line 50
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 51
      await testRunner.GivenAsync("Ana has created an invitation link to \"Checkout squad\" as editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 52
      await testRunner.WhenAsync("someone previews the invitation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
      await testRunner.ThenAsync("the request succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 54
      await testRunner.AndAsync("the preview says Ana invited them to \"Checkout squad\" as editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
      await testRunner.AndAsync("the invitation is valid", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A revoked invitation says so")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Invitations")]
        [global::Xunit.TraitAttribute("Description", "A revoked invitation says so")]
        public async global::System.Threading.Tasks.Task ARevokedInvitationSaysSo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A revoked invitation says so", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Preview an invitation", null, tagsOfRule);
#line 57
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 58
      await testRunner.GivenAsync("Ana has created an invitation link to \"Checkout squad\" as editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 59
      await testRunner.AndAsync("Ana has revoked the invitation", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
      await testRunner.WhenAsync("someone previews the invitation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
      await testRunner.ThenAsync("the invitation is revoked", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A made-up token finds nothing")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Invitations")]
        [global::Xunit.TraitAttribute("Description", "A made-up token finds nothing")]
        public async global::System.Threading.Tasks.Task AMade_UpTokenFindsNothing()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A made-up token finds nothing", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Preview an invitation", null, tagsOfRule);
#line 63
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 64
      await testRunner.WhenAsync("someone previews the invitation \"not-a-token\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
      await testRunner.ThenAsync("the request is refused as \"not-found\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Accepting a link joins the team with the invited role")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Invitations")]
        [global::Xunit.TraitAttribute("Description", "Accepting a link joins the team with the invited role")]
        public async global::System.Threading.Tasks.Task AcceptingALinkJoinsTheTeamWithTheInvitedRole()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Accepting a link joins the team with the invited role", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Accept an invitation", null, tagsOfRule);
#line 69
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 70
      await testRunner.GivenAsync("Ana has created an invitation link to \"Checkout squad\" as editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 71
      await testRunner.WhenAsync("Bo accepts the invitation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 72
      await testRunner.ThenAsync("the request succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 73
      await testRunner.AndAsync("Bo is an editor of \"Checkout squad\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A link can be used by several people")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Invitations")]
        [global::Xunit.TraitAttribute("Description", "A link can be used by several people")]
        public async global::System.Threading.Tasks.Task ALinkCanBeUsedBySeveralPeople()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A link can be used by several people", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Accept an invitation", null, tagsOfRule);
#line 75
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 76
      await testRunner.GivenAsync("Ana has created an invitation link to \"Checkout squad\" as viewer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 77
      await testRunner.AndAsync("Bo has accepted the invitation", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
      await testRunner.WhenAsync("Cy accepts the invitation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
      await testRunner.ThenAsync("Cy is a viewer of \"Checkout squad\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="An email invitation works once, and only for its address")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Invitations")]
        [global::Xunit.TraitAttribute("Description", "An email invitation works once, and only for its address")]
        public async global::System.Threading.Tasks.Task AnEmailInvitationWorksOnceAndOnlyForItsAddress()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An email invitation works once, and only for its address", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Accept an invitation", null, tagsOfRule);
#line 81
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 82
      await testRunner.GivenAsync("Ana has invited \"bo@example.com\" to \"Checkout squad\" as editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 83
      await testRunner.WhenAsync("Cy accepts the invitation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
      await testRunner.ThenAsync("the request is refused as \"forbidden\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 85
      await testRunner.AndAsync("Cy is not a member of \"Checkout squad\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="An email invitation cannot be used twice")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Invitations")]
        [global::Xunit.TraitAttribute("Description", "An email invitation cannot be used twice")]
        public async global::System.Threading.Tasks.Task AnEmailInvitationCannotBeUsedTwice()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An email invitation cannot be used twice", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Accept an invitation", null, tagsOfRule);
#line 87
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 88
      await testRunner.GivenAsync("Ana has invited \"bo@example.com\" to \"Checkout squad\" as editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 89
      await testRunner.AndAsync("Bo has accepted the invitation", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
      await testRunner.AndAsync("Bo leaves \"Checkout squad\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
      await testRunner.WhenAsync("Bo accepts the invitation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 92
      await testRunner.ThenAsync("the request fails with \"invitation-used\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Accepting again changes nothing")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Invitations")]
        [global::Xunit.TraitAttribute("Description", "Accepting again changes nothing")]
        public async global::System.Threading.Tasks.Task AcceptingAgainChangesNothing()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Accepting again changes nothing", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Accept an invitation", null, tagsOfRule);
#line 94
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 95
      await testRunner.GivenAsync("Ana has created an invitation link to \"Checkout squad\" as viewer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 96
      await testRunner.AndAsync("Bo has accepted the invitation", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
      await testRunner.WhenAsync("Bo accepts the invitation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 98
      await testRunner.ThenAsync("the request succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 99
      await testRunner.AndAsync("Bo is a viewer of \"Checkout squad\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="An expired invitation cannot be accepted")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Invitations")]
        [global::Xunit.TraitAttribute("Description", "An expired invitation cannot be accepted")]
        public async global::System.Threading.Tasks.Task AnExpiredInvitationCannotBeAccepted()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An expired invitation cannot be accepted", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Accept an invitation", null, tagsOfRule);
#line 101
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 102
      await testRunner.GivenAsync("Ana has created an invitation link to \"Checkout squad\" as editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 103
      await testRunner.AndAsync("8 days pass", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
      await testRunner.WhenAsync("Bo accepts the invitation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 105
      await testRunner.ThenAsync("the request fails with \"invitation-expired\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A revoked invitation cannot be accepted")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Invitations")]
        [global::Xunit.TraitAttribute("Description", "A revoked invitation cannot be accepted")]
        public async global::System.Threading.Tasks.Task ARevokedInvitationCannotBeAccepted()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A revoked invitation cannot be accepted", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Accept an invitation", null, tagsOfRule);
#line 107
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 108
      await testRunner.GivenAsync("Ana has created an invitation link to \"Checkout squad\" as editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 109
      await testRunner.AndAsync("Ana has revoked the invitation", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 110
      await testRunner.WhenAsync("Bo accepts the invitation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 111
      await testRunner.ThenAsync("the request fails with \"invitation-revoked\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await InvitationsFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await InvitationsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
