// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace EventStorming.Specs.Features.BoardModelling
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class BoardDocumentsAndAuto_LayoutFeature : object, Xunit.IClassFixture<BoardDocumentsAndAuto_LayoutFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/BoardModelling", "Board documents and auto-layout", @"  A whole board can be created or replaced from one Board Document - the format the public API and
  LLMs use. Array order is timeline order and positions are optional: whatever has none is laid out
  left to right, in its swimlane, inside its boundary, with room around pivotal events.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "BoardDocuments.feature"
#line hidden
        
        public BoardDocumentsAndAuto_LayoutFeature(BoardDocumentsAndAuto_LayoutFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("the time is \"2026-09-25T10:00:00Z\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("Ana owns the team \"Food delivery\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.AndAsync("Bo is a viewer of \"Food delivery\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/BoardModelling/BoardDocuments.feature.ndjson", 13);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A document without positions becomes a readable timeline")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Board documents and auto-layout")]
        [global::Xunit.TraitAttribute("Description", "A document without positions becomes a readable timeline")]
        public async global::System.Threading.Tasks.Task ADocumentWithoutPositionsBecomesAReadableTimeline()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A document without positions becomes a readable timeline", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Import a new board", null, tagsOfRule);
#line 13
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 14
      await testRunner.WhenAsync("Ana imports this document into \"Food delivery\":", @"{
  ""version"": 1,
  ""board"": { ""name"": ""Online food ordering"", ""level"": ""big-picture"" },
  ""elements"": [
    { ""key"": ""placed"", ""type"": ""domain-event"", ""text"": ""Order Placed"" },
    { ""key"": ""paid"", ""type"": ""domain-event"", ""text"": ""Payment Taken"" },
    { ""key"": ""late"", ""type"": ""hot-spot"", ""text"": ""What if the kitchen is busy?"", ""anchor"": ""paid"" },
    { ""key"": ""cooked"", ""type"": ""domain-event"", ""text"": ""Meal Cooked"" }
  ],
  ""connections"": [ { ""from"": ""placed"", ""to"": ""paid"" } ]
}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
      await testRunner.ThenAsync("the request succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "event"});
                table1.AddRow(new string[] {
                            "Order Placed"});
                table1.AddRow(new string[] {
                            "Payment Taken"});
                table1.AddRow(new string[] {
                            "Meal Cooked"});
#line 29
      await testRunner.AndAsync("the board \"Online food ordering\" reads left to right:", ((string)(null)), table1, "And ");
#line hidden
#line 34
      await testRunner.AndAsync("\"late\" is in the same column as \"paid\", below it", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
      await testRunner.AndAsync("\"placed\" is connected to \"paid\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Swimlanes stack, and each element sits inside its own")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Board documents and auto-layout")]
        [global::Xunit.TraitAttribute("Description", "Swimlanes stack, and each element sits inside its own")]
        public async global::System.Threading.Tasks.Task SwimlanesStackAndEachElementSitsInsideItsOwn()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Swimlanes stack, and each element sits inside its own", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Import a new board", null, tagsOfRule);
#line 37
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 38
      await testRunner.WhenAsync("Ana imports this document into \"Food delivery\":", @"{
  ""board"": { ""name"": ""Lanes"", ""level"": ""big-picture"" },
  ""elements"": [
    { ""key"": ""customer"", ""type"": ""swimlane"", ""text"": ""Customer"" },
    { ""key"": ""kitchen"", ""type"": ""swimlane"", ""text"": ""Kitchen"" },
    { ""key"": ""placed"", ""type"": ""domain-event"", ""text"": ""Order Placed"", ""swimlane"": ""customer"" },
    { ""key"": ""cooked"", ""type"": ""domain-event"", ""text"": ""Meal Cooked"", ""swimlane"": ""kitchen"" }
  ]
}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
      await testRunner.ThenAsync("the request succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 51
      await testRunner.AndAsync("\"placed\" is inside \"customer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
      await testRunner.AndAsync("\"cooked\" is inside \"kitchen\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
      await testRunner.AndAsync("\"customer\" is above \"kitchen\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
      await testRunner.AndAsync("\"placed\" is left of \"cooked\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A boundary surrounds its members, and only them")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Board documents and auto-layout")]
        [global::Xunit.TraitAttribute("Description", "A boundary surrounds its members, and only them")]
        public async global::System.Threading.Tasks.Task ABoundarySurroundsItsMembersAndOnlyThem()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A boundary surrounds its members, and only them", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Import a new board", null, tagsOfRule);
#line 56
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 57
      await testRunner.WhenAsync("Ana imports this document into \"Food delivery\":", @"{
  ""board"": { ""name"": ""Contexts"", ""level"": ""big-picture"" },
  ""elements"": [
    { ""key"": ""ordering"", ""type"": ""boundary"", ""text"": ""Ordering"" },
    { ""key"": ""placed"", ""type"": ""domain-event"", ""text"": ""Order Placed"", ""boundary"": ""ordering"" },
    { ""key"": ""paid"", ""type"": ""domain-event"", ""text"": ""Payment Taken"", ""boundary"": ""ordering"" },
    { ""key"": ""cooked"", ""type"": ""domain-event"", ""text"": ""Meal Cooked"" }
  ]
}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
      await testRunner.ThenAsync("\"placed\" is inside \"ordering\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 70
      await testRunner.AndAsync("\"paid\" is inside \"ordering\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
      await testRunner.AndAsync("\"cooked\" is not inside \"ordering\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Pivotal events get room around them")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Board documents and auto-layout")]
        [global::Xunit.TraitAttribute("Description", "Pivotal events get room around them")]
        public async global::System.Threading.Tasks.Task PivotalEventsGetRoomAroundThem()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pivotal events get room around them", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Import a new board", null, tagsOfRule);
#line 73
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 74
      await testRunner.WhenAsync("Ana imports this document into \"Food delivery\":", @"{
  ""board"": { ""name"": ""Pivots"", ""level"": ""big-picture"" },
  ""elements"": [
    { ""key"": ""a"", ""type"": ""domain-event"", ""text"": ""Basket Filled"" },
    { ""key"": ""b"", ""type"": ""domain-event"", ""text"": ""Order Placed"", ""pivotal"": true },
    { ""key"": ""c"", ""type"": ""domain-event"", ""text"": ""Payment Taken"" },
    { ""key"": ""d"", ""type"": ""domain-event"", ""text"": ""Receipt Sent"" }
  ]
}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 86
      await testRunner.ThenAsync("the gap before \"b\" is wider than the gap before \"d\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Explicit positions are kept")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Board documents and auto-layout")]
        [global::Xunit.TraitAttribute("Description", "Explicit positions are kept")]
        public async global::System.Threading.Tasks.Task ExplicitPositionsAreKept()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Explicit positions are kept", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Import a new board", null, tagsOfRule);
#line 88
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 89
      await testRunner.WhenAsync("Ana imports this document into \"Food delivery\":", "{\r\n  \"board\": { \"name\": \"Positioned\", \"level\": \"big-picture\" },\r\n  \"elements\": [\r" +
                        "\n    { \"key\": \"placed\", \"type\": \"domain-event\", \"text\": \"Order Placed\", \"positio" +
                        "n\": { \"x\": 500, \"y\": 300 } }\r\n  ]\r\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 98
      await testRunner.ThenAsync("\"placed\" keeps its position 500,300", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Every mistake in a document is reported at once, with a fix")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Board documents and auto-layout")]
        [global::Xunit.TraitAttribute("Description", "Every mistake in a document is reported at once, with a fix")]
        public async global::System.Threading.Tasks.Task EveryMistakeInADocumentIsReportedAtOnceWithAFix()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Every mistake in a document is reported at once, with a fix", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Import a new board", null, tagsOfRule);
#line 100
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 101
      await testRunner.WhenAsync("Ana imports this document into \"Food delivery\":", @"{
  ""version"": 2,
  ""board"": { ""level"": ""detailed"" },
  ""elements"": [
    { ""key"": ""placed"", ""type"": ""domain-event"", ""text"": ""Order Placed"" },
    { ""key"": ""placed"", ""type"": ""event"", ""text"": ""Order Paid"" },
    { ""key"": ""lane"", ""type"": ""domain-event"", ""text"": ""Kitchen"" },
    { ""key"": ""cooked"", ""type"": ""domain-event"", ""text"": ""Meal Cooked"", ""swimlane"": ""lane"" }
  ],
  ""connections"": [ { ""from"": ""placed"", ""to"": ""cookd"" } ]
}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "code"});
                table2.AddRow(new string[] {
                            "version",
                            "unsupported-version"});
                table2.AddRow(new string[] {
                            "board.level",
                            "unknown-level"});
                table2.AddRow(new string[] {
                            "board.name",
                            "required"});
                table2.AddRow(new string[] {
                            "elements[1].key",
                            "duplicate-key"});
#line 115
      await testRunner.ThenAsync("the request fails with these failures:", ((string)(null)), table2, "Then ");
#line hidden
#line 121
      await testRunner.AndAsync("every failure says how to fix it", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="References must point at the right kind of element")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Board documents and auto-layout")]
        [global::Xunit.TraitAttribute("Description", "References must point at the right kind of element")]
        public async global::System.Threading.Tasks.Task ReferencesMustPointAtTheRightKindOfElement()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("References must point at the right kind of element", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Import a new board", null, tagsOfRule);
#line 123
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 124
      await testRunner.WhenAsync("Ana imports this document into \"Food delivery\":", @"{
  ""board"": { ""name"": ""Refs"", ""level"": ""big-picture"" },
  ""elements"": [
    { ""key"": ""lane"", ""type"": ""domain-event"", ""text"": ""Kitchen"" },
    { ""key"": ""cooked"", ""type"": ""domain-event"", ""text"": ""Meal Cooked"", ""swimlane"": ""lane"" }
  ],
  ""connections"": [ { ""from"": ""cooked"", ""to"": ""cookd"" } ]
}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "field",
                            "code"});
                table3.AddRow(new string[] {
                            "elements[1].swimlane",
                            "not-a-swimlane"});
                table3.AddRow(new string[] {
                            "connections[0].to",
                            "unknown-reference"});
#line 135
      await testRunner.ThenAsync("the request fails with these failures:", ((string)(null)), table3, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Viewers cannot import")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Board documents and auto-layout")]
        [global::Xunit.TraitAttribute("Description", "Viewers cannot import")]
        public async global::System.Threading.Tasks.Task ViewersCannotImport()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Viewers cannot import", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Import a new board", null, tagsOfRule);
#line 140
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 141
      await testRunner.WhenAsync("Bo imports this document into \"Food delivery\":", "{ \"board\": { \"name\": \"Mine\", \"level\": \"big-picture\" }, \"elements\": [] }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 145
      await testRunner.ThenAsync("the request is refused as \"forbidden\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Replacing swaps all the content and tells open boards to reload")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Board documents and auto-layout")]
        [global::Xunit.TraitAttribute("Description", "Replacing swaps all the content and tells open boards to reload")]
        public async global::System.Threading.Tasks.Task ReplacingSwapsAllTheContentAndTellsOpenBoardsToReload()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Replacing swaps all the content and tells open boards to reload", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Replace a board\'s content", null, tagsOfRule);
#line 155
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 150
      await testRunner.GivenAsync("\"Food delivery\" has a \"big-picture\" board called \"Ordering\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "key",
                            "type",
                            "text"});
                table4.AddRow(new string[] {
                            "old",
                            "domain-event",
                            "Old Event"});
#line 151
      await testRunner.AndAsync("the board \"Ordering\" has these elements:", ((string)(null)), table4, "And ");
#line hidden
#line 156
      await testRunner.WhenAsync("Ana replaces the content of \"Ordering\" with:", "{ \"elements\": [ { \"key\": \"new\", \"type\": \"domain-event\", \"text\": \"New Event\" } ] }" +
                        "", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 160
      await testRunner.ThenAsync("the request succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 161
      await testRunner.AndAsync("the board \"Ordering\" has 1 element", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 162
      await testRunner.AndAsync("the element \"new\" says \"New Event\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 163
      await testRunner.AndAsync("the whole content change is announced for \"Ordering\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="The level of an existing board cannot change")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Board documents and auto-layout")]
        [global::Xunit.TraitAttribute("Description", "The level of an existing board cannot change")]
        public async global::System.Threading.Tasks.Task TheLevelOfAnExistingBoardCannotChange()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The level of an existing board cannot change", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Replace a board\'s content", null, tagsOfRule);
#line 165
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 150
      await testRunner.GivenAsync("\"Food delivery\" has a \"big-picture\" board called \"Ordering\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "key",
                            "type",
                            "text"});
                table5.AddRow(new string[] {
                            "old",
                            "domain-event",
                            "Old Event"});
#line 151
      await testRunner.AndAsync("the board \"Ordering\" has these elements:", ((string)(null)), table5, "And ");
#line hidden
#line 166
      await testRunner.WhenAsync("Ana replaces the content of \"Ordering\" with:", "{ \"board\": { \"level\": \"software-design\" }, \"elements\": [] }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 170
      await testRunner.ThenAsync("the request fails with \"level-immutable\" on \"board.level\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="An export can be imported again, exactly as it was")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Board documents and auto-layout")]
        [global::Xunit.TraitAttribute("Description", "An export can be imported again, exactly as it was")]
        public async global::System.Threading.Tasks.Task AnExportCanBeImportedAgainExactlyAsItWas()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An export can be imported again, exactly as it was", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Export a board", null, tagsOfRule);
#line 177
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 175
      await testRunner.GivenAsync("\"Food delivery\" has a \"big-picture\" board called \"Ordering\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 178
      await testRunner.GivenAsync("Ana has replaced the content of \"Ordering\" with:", @"{
  ""elements"": [
    { ""key"": ""customer"", ""type"": ""swimlane"", ""text"": ""Customer"" },
    { ""key"": ""placed"", ""type"": ""domain-event"", ""text"": ""Order Placed"", ""swimlane"": ""customer"" },
    { ""key"": ""paid"", ""type"": ""domain-event"", ""text"": ""Payment Taken"", ""swimlane"": ""customer"" }
  ],
  ""connections"": [ { ""from"": ""placed"", ""to"": ""paid"" } ]
}", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 189
      await testRunner.WhenAsync("Bo exports \"Ordering\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 190
      await testRunner.ThenAsync("the request succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 191
      await testRunner.AndAsync("the export has 3 elements and 1 connection", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 192
      await testRunner.AndAsync("the export says \"placed\" sits in the swimlane \"customer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 193
      await testRunner.WhenAsync("Ana imports that export into \"Food delivery\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 194
      await testRunner.ThenAsync("the request succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 195
      await testRunner.AndAsync("the copy has every element where the original had it", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await BoardDocumentsAndAuto_LayoutFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await BoardDocumentsAndAuto_LayoutFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
