// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace EventStorming.Specs.Features.BoardModelling
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TheBoardCatalogFeature : object, Xunit.IClassFixture<TheBoardCatalogFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/BoardModelling", "The board catalog", "  A team\'s dashboard lists its boards. Owners and Editors create, rename, duplica" +
                "te, archive and\r\n  restore them; Viewers can only look. A board\'s level is chose" +
                "n when it is created.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "BoardCatalog.feature"
#line hidden
        
        public TheBoardCatalogFeature(TheBoardCatalogFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 5
  #line hidden
#line 6
    await testRunner.GivenAsync("the time is \"2026-09-25T10:00:00Z\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
    await testRunner.AndAsync("Ana owns the team \"Food delivery\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
    await testRunner.AndAsync("Bo is a viewer of \"Food delivery\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/BoardModelling/BoardCatalog.feature.ndjson", 17);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="An Editor creates a board at any level")]
        [global::Xunit.TraitAttribute("FeatureTitle", "The board catalog")]
        [global::Xunit.TraitAttribute("Description", "An Editor creates a board at any level")]
        [global::Xunit.InlineDataAttribute("big-picture", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("process-modelling", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("software-design", "2", new string[0])]
        public async global::System.Threading.Tasks.Task AnEditorCreatesABoardAtAnyLevel(string level, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("level", level);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An Editor creates a board at any level", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Create a board", null, tagsOfRule);
#line 12
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 13
      await testRunner.WhenAsync(string.Format("Ana creates a \"{0}\" board called \"Ordering\" in \"Food delivery\"", level), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
      await testRunner.ThenAsync("the request succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 15
      await testRunner.AndAsync(string.Format("\"Food delivery\" has a board called \"Ordering\" at the \"{0}\" level", level), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="The level must be one of the three")]
        [global::Xunit.TraitAttribute("FeatureTitle", "The board catalog")]
        [global::Xunit.TraitAttribute("Description", "The level must be one of the three")]
        public async global::System.Threading.Tasks.Task TheLevelMustBeOneOfTheThree()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The level must be one of the three", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Create a board", null, tagsOfRule);
#line 23
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 24
      await testRunner.WhenAsync("Ana creates a \"detailed\" board called \"Ordering\" in \"Food delivery\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
      await testRunner.ThenAsync("the request fails with \"unknown-level\" on \"level\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 26
      await testRunner.AndAsync("every failure says how to fix it", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Viewers cannot create boards")]
        [global::Xunit.TraitAttribute("FeatureTitle", "The board catalog")]
        [global::Xunit.TraitAttribute("Description", "Viewers cannot create boards")]
        public async global::System.Threading.Tasks.Task ViewersCannotCreateBoards()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Viewers cannot create boards", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Create a board", null, tagsOfRule);
#line 28
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 29
      await testRunner.WhenAsync("Bo creates a \"big-picture\" board called \"Ordering\" in \"Food delivery\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
      await testRunner.ThenAsync("the request is refused as \"forbidden\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Outsiders cannot even tell the team exists")]
        [global::Xunit.TraitAttribute("FeatureTitle", "The board catalog")]
        [global::Xunit.TraitAttribute("Description", "Outsiders cannot even tell the team exists")]
        public async global::System.Threading.Tasks.Task OutsidersCannotEvenTellTheTeamExists()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Outsiders cannot even tell the team exists", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Create a board", null, tagsOfRule);
#line 32
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 33
      await testRunner.GivenAsync("Cy has an account", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 34
      await testRunner.WhenAsync("Cy creates a \"big-picture\" board called \"Ordering\" in \"Food delivery\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
      await testRunner.ThenAsync("the request is refused as \"not-found\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="The dashboard shows live boards, most recently changed first")]
        [global::Xunit.TraitAttribute("FeatureTitle", "The board catalog")]
        [global::Xunit.TraitAttribute("Description", "The dashboard shows live boards, most recently changed first")]
        public async global::System.Threading.Tasks.Task TheDashboardShowsLiveBoardsMostRecentlyChangedFirst()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The dashboard shows live boards, most recently changed first", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("List the boards", null, tagsOfRule);
#line 39
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 40
      await testRunner.GivenAsync("\"Food delivery\" has a \"big-picture\" board called \"Whole business\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 41
      await testRunner.AndAsync("\"Food delivery\" has a \"process-modelling\" board called \"Checkout\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
      await testRunner.AndAsync("\"Food delivery\" has a \"big-picture\" board called \"Old ideas\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
      await testRunner.AndAsync("the board \"Old ideas\" is archived", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
      await testRunner.WhenAsync("Bo lists the boards of \"Food delivery\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
      await testRunner.ThenAsync("the request succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "board"});
                table1.AddRow(new string[] {
                            "Checkout"});
                table1.AddRow(new string[] {
                            "Whole business"});
#line 46
      await testRunner.AndAsync("the boards listed are, most recent first:", ((string)(null)), table1, "And ");
#line hidden
#line 50
      await testRunner.AndAsync("they may view the team\'s boards", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Archived boards can be listed too")]
        [global::Xunit.TraitAttribute("FeatureTitle", "The board catalog")]
        [global::Xunit.TraitAttribute("Description", "Archived boards can be listed too")]
        public async global::System.Threading.Tasks.Task ArchivedBoardsCanBeListedToo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Archived boards can be listed too", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("List the boards", null, tagsOfRule);
#line 52
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 53
      await testRunner.GivenAsync("\"Food delivery\" has a \"big-picture\" board called \"Old ideas\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 54
      await testRunner.AndAsync("the board \"Old ideas\" is archived", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
      await testRunner.WhenAsync("Ana lists the boards of \"Food delivery\" including archived ones", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "board"});
                table2.AddRow(new string[] {
                            "Old ideas"});
#line 56
      await testRunner.ThenAsync("the boards listed are, most recent first:", ((string)(null)), table2, "Then ");
#line hidden
#line 59
      await testRunner.AndAsync("they may edit the team\'s boards", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Long lists come in pages")]
        [global::Xunit.TraitAttribute("FeatureTitle", "The board catalog")]
        [global::Xunit.TraitAttribute("Description", "Long lists come in pages")]
        public async global::System.Threading.Tasks.Task LongListsComeInPages()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Long lists come in pages", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("List the boards", null, tagsOfRule);
#line 61
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 62
      await testRunner.GivenAsync("\"Food delivery\" has a \"big-picture\" board called \"One\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 63
      await testRunner.AndAsync("\"Food delivery\" has a \"big-picture\" board called \"Two\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
      await testRunner.AndAsync("\"Food delivery\" has a \"big-picture\" board called \"Three\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
      await testRunner.WhenAsync("Ana lists the boards of \"Food delivery\" 2 at a time", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "board"});
                table3.AddRow(new string[] {
                            "Three"});
                table3.AddRow(new string[] {
                            "Two"});
#line 66
      await testRunner.ThenAsync("the boards listed are, most recent first:", ((string)(null)), table3, "Then ");
#line hidden
#line 70
      await testRunner.AndAsync("the listing has a next page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A cursor must be one the API issued")]
        [global::Xunit.TraitAttribute("FeatureTitle", "The board catalog")]
        [global::Xunit.TraitAttribute("Description", "A cursor must be one the API issued")]
        public async global::System.Threading.Tasks.Task ACursorMustBeOneTheAPIIssued()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A cursor must be one the API issued", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("List the boards", null, tagsOfRule);
#line 72
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 73
      await testRunner.WhenAsync("Ana lists the boards of \"Food delivery\" from the cursor \"made-up\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 74
      await testRunner.ThenAsync("the request fails with \"invalid-cursor\" on \"cursor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Renaming a board tells everyone who has it open")]
        [global::Xunit.TraitAttribute("FeatureTitle", "The board catalog")]
        [global::Xunit.TraitAttribute("Description", "Renaming a board tells everyone who has it open")]
        public async global::System.Threading.Tasks.Task RenamingABoardTellsEveryoneWhoHasItOpen()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Renaming a board tells everyone who has it open", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Change a board", null, tagsOfRule);
#line 78
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 79
      await testRunner.GivenAsync("\"Food delivery\" has a \"big-picture\" board called \"Draft\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 80
      await testRunner.WhenAsync("Ana renames the board \"Draft\" to \"Food ordering\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
      await testRunner.ThenAsync("the request succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 82
      await testRunner.AndAsync("the new name is announced to everyone on the board", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Viewers cannot rename")]
        [global::Xunit.TraitAttribute("FeatureTitle", "The board catalog")]
        [global::Xunit.TraitAttribute("Description", "Viewers cannot rename")]
        public async global::System.Threading.Tasks.Task ViewersCannotRename()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Viewers cannot rename", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Change a board", null, tagsOfRule);
#line 84
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 85
      await testRunner.GivenAsync("\"Food delivery\" has a \"big-picture\" board called \"Draft\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 86
      await testRunner.WhenAsync("Bo renames the board \"Draft\" to \"Mine now\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 87
      await testRunner.ThenAsync("the request is refused as \"forbidden\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Archiving makes a board read-only, restoring brings it back")]
        [global::Xunit.TraitAttribute("FeatureTitle", "The board catalog")]
        [global::Xunit.TraitAttribute("Description", "Archiving makes a board read-only, restoring brings it back")]
        public async global::System.Threading.Tasks.Task ArchivingMakesABoardRead_OnlyRestoringBringsItBack()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Archiving makes a board read-only, restoring brings it back", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Change a board", null, tagsOfRule);
#line 89
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 90
      await testRunner.GivenAsync("\"Food delivery\" has a \"big-picture\" board called \"Draft\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 91
      await testRunner.WhenAsync("Ana archives the board \"Draft\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 92
      await testRunner.ThenAsync("the board \"Draft\" is archived", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 93
      await testRunner.AndAsync("the change of state is announced to everyone on the board", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 94
      await testRunner.WhenAsync("Ana renames the board \"Draft\" to \"Still editing\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 95
      await testRunner.ThenAsync("the request fails with \"board-archived\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 96
      await testRunner.WhenAsync("Ana restores the board \"Draft\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 97
      await testRunner.ThenAsync("the board \"Draft\" is not archived", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Members open a board with the permission their role gives them")]
        [global::Xunit.TraitAttribute("FeatureTitle", "The board catalog")]
        [global::Xunit.TraitAttribute("Description", "Members open a board with the permission their role gives them")]
        public async global::System.Threading.Tasks.Task MembersOpenABoardWithThePermissionTheirRoleGivesThem()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Members open a board with the permission their role gives them", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Open a board", null, tagsOfRule);
#line 101
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 102
      await testRunner.GivenAsync("\"Food delivery\" has a \"big-picture\" board called \"Whole business\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 103
      await testRunner.WhenAsync("Bo opens the board \"Whole business\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 104
      await testRunner.ThenAsync("the request succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 105
      await testRunner.AndAsync("they can view the board", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
      await testRunner.WhenAsync("Ana looks up the board \"Whole business\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 107
      await testRunner.ThenAsync("they can edit the board", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Everyone can read the element types and levels")]
        [global::Xunit.TraitAttribute("FeatureTitle", "The board catalog")]
        [global::Xunit.TraitAttribute("Description", "Everyone can read the element types and levels")]
        public async global::System.Threading.Tasks.Task EveryoneCanReadTheElementTypesAndLevels()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Everyone can read the element types and levels", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The notation", null, tagsOfRule);
#line 111
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
  await this.FeatureBackgroundAsync();
#line hidden
#line 112
      await testRunner.WhenAsync("Ana asks for the element types", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 113
      await testRunner.ThenAsync("the notation lists 11 element types and 3 levels", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await TheBoardCatalogFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await TheBoardCatalogFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
